FROM alpine:latest

# 安装必要的软件包
RUN apk add --no-cache wget bash openssl socat nginx iputils tar xz libstdc++ libc6-compat iproute2 net-tools

# 设置环境变量
ENV DOMAIN=example.com
ENV FORCE_LOCAL=false
ENV TROJAN_PW=

# 创建存储目录
RUN mkdir -p ~/.acme.sh/ /opt/scripts/

# 复制脚本
COPY scripts /opt/scripts/

# 设置工作目录
WORKDIR /opt/scripts

# 复制html
COPY config /usr/share/nginx/html/

# 暴露端口
EXPOSE 80 443

#使用JSON数组格式指定CMD
CMD ["bash", "install.environment.sh"]